# Generated by Django 5.2.4 on 2026-06-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('territory', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', max_length=200)),
                ('name_normalized', models.CharField(blank=True, db_index=True, help_text='Lowercased, stripped name used for duplicate detection.', max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['store_name'],
                'constraints': [models.UniqueConstraint(fields=('name_normalized', 'area'), name='unique_store_name_area')],
            },
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date the rep recorded or submitted this report.')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='visit_reports/%Y/%m/%d/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_reports', to='crm.salesrep')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(help_text='Date this specific store visit occurred.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('FOLLOW_UP_NEEDED', 'Follow-Up Needed'), ('NO_REQUIREMENT', 'No Requirement'), ('NOT_INTERESTED', 'Not Interested')], default='PENDING', max_length=30)),
                ('quantity_requested', models.PositiveIntegerField(blank=True, help_text='Number of bags requested or ordered.', null=True)),
                ('rate_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Price per bag discussed during the visit.', max_digits=10, null=True)),
                ('needed_by_date', models.DateField(blank=True, help_text='When the store needs the bags, if mentioned.', null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='crm.store')),
                ('visit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to='crm.visitreport')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['visit_date'], name='crm_storevi_visit_d_e73d96_idx'), models.Index(fields=['status'], name='crm_storevi_status_baf428_idx'), models.Index(fields=['follow_up_required', 'follow_up_completed'], name='crm_storevi_follow__63fb6a_idx'), models.Index(fields=['visit_report', 'visit_date'], name='crm_storevi_visit_r_e84a0a_idx')],
            },
        ),
    ]
