# Generated by Django 6.0.6 on 2026-06-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the sales representative', max_length=150)),
                ('phone', models.CharField(help_text='Primary contact number', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('territory', models.CharField(blank=True, help_text='Assigned market region or city zone', max_length=100, null=True)),
                ('joining_date', models.DateField(help_text='Employment start date')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to soft-delete inactive employees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_sales_rep',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='Store name as spoken or displayed', max_length=200)),
                ('store_name_normalized', models.CharField(blank=True, db_index=True, max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(blank=True, help_text='Neighborhood or locality', max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='The actual date the field visits took place')),
                ('audio_file', models.FileField(help_text='Path to stored audio binary', upload_to='voice_notes/%Y/%m/%d/')),
                ('transcript', models.TextField(blank=True, help_text='Verbatim output text from Whisper transcription', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_reports', to='crm.salesrep')),
            ],
            options={
                'db_table': 'crm_visit_report',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('INTERESTED', 'Interested'), ('ORDER_PLACED', 'Order Placed'), ('NO_REQUIREMENT', 'No Requirement'), ('FOLLOW_UP_NEEDED', 'Follow Up Needed'), ('LOST_OPPORTUNITY', 'Lost Opportunity')], help_text='Outcome classification', max_length=30)),
                ('quantity_requested', models.PositiveIntegerField(default=0, help_text='Number of bags ordered or requested')),
                ('price_per_bag', models.DecimalField(blank=True, decimal_places=2, help_text='Price per bag in PKR', max_digits=10, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, help_text='Contextual notes or specific customer instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to='crm.store')),
                ('visit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_visits', to='crm.visitreport')),
            ],
            options={
                'db_table': 'crm_store_visit',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
