# Generated by Django 6.0.6 on 2026-06-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of field representative', max_length=150)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20, unique=True)),
                ('whatsapp_id', models.CharField(blank=True, help_text='WhatsApp sender ID for Phase 2 attribution', max_length=50, null=True, unique=True)),
                ('area', models.CharField(blank=True, help_text='Assigned territory or city zone', max_length=100, null=True)),
                ('joining_date', models.DateField(help_text='Date of employment start')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag; inactive employees excluded from assignments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_employee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store display name as spoken', max_length=200)),
                ('name_normalized', models.CharField(blank=True, db_index=True, help_text='Lowercased, stripped for dedup comparison', max_length=200)),
                ('area', models.CharField(blank=True, help_text='Neighborhood or zone', max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text='Full street address', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude for map view', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude for map view', max_digits=10, null=True)),
                ('owner_name', models.CharField(blank=True, help_text='Shop owner or buyer contact name', max_length=150, null=True)),
                ('owner_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_requested', models.PositiveIntegerField(blank=True, help_text='Number of rice bags requested', null=True)),
                ('price_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Price per bag quoted by rep (PKR)', max_digits=10, null=True)),
                ('rice_variety', models.CharField(blank=True, help_text='e.g. Basmati, Sella, IRRI', max_length=100, null=True)),
                ('status', models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('FOLLOW_UP_REQUIRED', 'Follow-Up Required'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('DELIVERY_SCHEDULED', 'Delivery Scheduled'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='NEW_LEAD', help_text='Cached current status', max_length=40)),
                ('notes', models.TextField(blank=True, help_text='Free-form text context details', null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.store')),
            ],
            options={
                'db_table': 'crm_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Target date for follow-up action')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_followups', to='crm.employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_followup',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('bags_delivered', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_deliveries', to='crm.employee')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_delivery',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(help_text='Relative path under MEDIA_ROOT', max_length=500, upload_to='voice_notes/%Y/%m/%d/')),
                ('file_format', models.CharField(help_text='mp3 / ogg / m4a / wav / webm', max_length=10)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Raw Whisper output (verbatim)', null=True)),
                ('transcript_confidence', models.DecimalField(blank=True, decimal_places=4, help_text='Whisper confidence score 0.0-1.0', max_digits=5, null=True)),
                ('extracted_json', models.JSONField(blank=True, help_text='Raw GPT extraction output stored for debugging', null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('TRANSCRIBING', 'Transcribing'), ('EXTRACTING', 'Extracting'), ('AWAITING_REVIEW', 'Awaiting Review'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Meta message ID for Phase 2 dedup', max_length=100, null=True, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes', to='crm.employee')),
            ],
            options={
                'db_table': 'crm_voicenote',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('actor_type', models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('actor_id', models.IntegerField(blank=True, help_text='ID of Employee or User who triggered transition', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('voice_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.voicenote')),
            ],
            options={
                'db_table': 'crm_leadactivity',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='voice_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.voicenote'),
        ),
    ]
