# Generated by Django 5.2.4 on 2026-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_store_name_area',
        ),
        migrations.AddField(
            model_name='store',
            name='owner_normalized',
            field=models.CharField(blank=True, db_index=True, help_text='Lowercased, stripped owner name used for duplicate detection.', max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text='Shop owner name — required for disambiguating same-named stores.', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('name_normalized', 'owner_normalized', 'area'), name='unique_store_identity'),
        ),
    ]
