# Generated by Django 5.2.4 on 2026-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_store_unique_store_name_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSCRIBED', 'Transcribed'), ('EXTRACTED', 'Extracted'), ('REVIEWED', 'Reviewed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Voice note audio (mp3, m4a, ogg, wav).', null=True, upload_to='visit_reports/%Y/%m/%d/'),
        ),
    ]
