# Generated by Django 5.2.4 on 2026-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_visitreport_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='extraction_payload',
            field=models.JSONField(blank=True, help_text='AI extraction output, auto-created visit IDs, and items needing review.', null=True),
        ),
    ]
